#!/bin/sh
# /etc/init.d/wetcat

### BEGIN INIT INFO
# Provides:          wetcat
# Required-Start:    $remote_fs $syslog $all
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

case "$1" in
  start)
    echo "Starting wetcat"
    sudo -u pi -H bash -c "nohup /usr/bin/python3 /home/pi/dev/WetCat/start.py &"
    ;;
  stop)
    echo "Stopping wetcat"
    killall python3
    ;;
  *)
    echo "Usage: /etc/init.d/wetcat {start|stop}"
    exit 1
    ;;
esac

exit 0
